# Generated by Django 6.0.4 on 2026-05-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_anonymouse',
            new_name='is_anonymous',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_anonymouse',
            new_name='is_anonymous',
        ),
    ]
