# Generated by Django 6.0.3 on 2026-05-10 02:29

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=posts.models.upload_filepath),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=1, upload_to=posts.models.upload_filepath),
            preserve_default=False,
        ),
    ]
